-- =====================================================================
-- 0001_schema.sql
-- App de Pesquisa de Concorrentes Imobiliários — modelagem inicial
-- Fonte: prompt de especificação (seções 7–25, 39, 43, 44) +
--        planilha Comparativo_Normalizado_App_v2.xlsx
--
-- Hierarquia:  REGIONAL -> CIDADE -> EMPREENDIMENTO -> CONCORRENTE
-- Coletas:     AGENTE 1:N COLETA ; CONCORRENTE 1:N COLETA
-- Próprios:    EMPREENDIMENTO 1:N DADOS_PROPRIOS_MENSAIS
--
-- Banco: PostgreSQL simples (Railway), sem dependência de nenhum serviço
-- externo. gen_random_uuid() é nativo desde o PostgreSQL 13 (sem extensão).
-- Autenticação e autorização do Gestor são inteiramente da aplicação
-- (bcrypt + sessão JWT em cookie — ver src/lib/auth); não há RLS aqui.
-- =====================================================================

-- ---------------------------------------------------------------------
-- REGIONAIS  (seção 8) — a própria sigla é a PK
-- ---------------------------------------------------------------------
create table if not exists regionais (
  regional text primary key
);

-- ---------------------------------------------------------------------
-- CIDADES  (seção 9) — REGIONAIS 1:N CIDADES
-- Não permitir a mesma cidade duplicada dentro da mesma regional.
-- ---------------------------------------------------------------------
create table if not exists cidades (
  id_cidade integer generated by default as identity primary key,
  regional  text not null references regionais (regional) on update cascade,
  cidade    text not null,
  constraint uq_cidade_por_regional unique (regional, cidade)
);
create index if not exists idx_cidades_regional on cidades (regional);

-- ---------------------------------------------------------------------
-- EMPREENDIMENTOS  (seção 10) — CIDADES 1:N EMPREENDIMENTOS
-- id_empreendimento vem da base (não é gerado): é o prefixo dos IDs de
-- concorrentes, então é uma PK inteira informada pela seed/gestor.
-- ---------------------------------------------------------------------
create table if not exists empreendimentos (
  id_empreendimento integer primary key,
  id_cidade         integer not null references cidades (id_cidade),
  empreendimento    text not null,
  ativo             boolean not null default true
);
create index if not exists idx_empreendimentos_id_cidade on empreendimentos (id_cidade);

-- ---------------------------------------------------------------------
-- GESTORES  (seção 2, 3) — perfil administrativo.
-- Autenticação própria: senha_hash guarda o hash bcrypt (nunca a senha).
-- email é único ignorando maiúsculas/minúsculas.
-- ---------------------------------------------------------------------
create table if not exists gestores (
  id_gestor  uuid primary key default gen_random_uuid(),
  nome       text not null,
  email      text not null,
  senha_hash text not null,
  perfil     text not null default 'gestor' check (perfil = 'gestor'),
  ativo      boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists uq_gestores_email_lower on gestores (lower(email));

-- ---------------------------------------------------------------------
-- CONCORRENTES  (seção 11, 12) — EMPREENDIMENTOS 1:N CONCORRENTES
-- id_concorrente é inteiro cujo PREFIXO é o id_empreendimento pai.
-- É gerado no backend (ver 0002_id_concorrente.sql), por isso a PK é
-- informada e não "identity".
-- Nome único (case-insensitive, trim) dentro do mesmo empreendimento.
-- ---------------------------------------------------------------------
create table if not exists concorrentes (
  id_concorrente    integer primary key,
  id_empreendimento integer not null references empreendimentos (id_empreendimento),
  concorrente       text not null,
  ativo             boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  created_by        uuid references gestores (id_gestor),
  updated_by        uuid references gestores (id_gestor)
);
create index if not exists idx_concorrentes_id_empreendimento on concorrentes (id_empreendimento);

-- Unicidade de nome por empreendimento ignorando caixa e espaços nas pontas.
create unique index if not exists uq_concorrente_nome_por_emp
  on concorrentes (id_empreendimento, lower(btrim(concorrente)));

-- ---------------------------------------------------------------------
-- AGENTES_CAMPO  (seção 4, 5, 6) — acesso apenas pelo telefone.
-- telefone armazenado JÁ normalizado (somente dígitos) e é único.
-- Não excluir fisicamente: usar ativo=false.
-- ---------------------------------------------------------------------
create table if not exists agentes_campo (
  id_agente  uuid primary key default gen_random_uuid(),
  nome       text not null,
  telefone   text not null unique,      -- somente dígitos
  ativo      boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references gestores (id_gestor),
  updated_by uuid references gestores (id_gestor),
  constraint chk_telefone_digitos check (telefone ~ '^[0-9]+$')
);
create index if not exists idx_agentes_campo_telefone on agentes_campo (telefone);

-- ---------------------------------------------------------------------
-- COLETAS_MENSAIS  (seção 22, 23) — a pesquisa em si.
-- Não repetir textos de regional/cidade/empreendimento/concorrente/agente:
-- tudo vem por relacionamento.
-- mes_ano = primeiro dia do mês (YYYY-MM-01).
-- UNIQUE(id_concorrente, mes_ano): uma coleta por concorrente por mês.
-- ---------------------------------------------------------------------
create table if not exists coletas_mensais (
  id_coleta      uuid primary key default gen_random_uuid(),
  id_agente      uuid not null references agentes_campo (id_agente),
  id_concorrente integer not null references concorrentes (id_concorrente),
  mes_ano        date not null,
  estoque        integer not null check (estoque >= 0),
  vendas         integer not null check (vendas  >= 0),
  coletado_em    timestamptz not null default now(),
  atualizado_em  timestamptz not null default now(),
  constraint chk_mes_ano_dia1 check (date_trunc('month', mes_ano) = mes_ano),
  constraint uq_coleta_concorrente_mes unique (id_concorrente, mes_ano)
);
create index if not exists idx_coletas_id_concorrente on coletas_mensais (id_concorrente);
create index if not exists idx_coletas_mes_ano        on coletas_mensais (mes_ano);
create index if not exists idx_coletas_id_agente      on coletas_mensais (id_agente);

-- ---------------------------------------------------------------------
-- DADOS_PROPRIOS_MENSAIS  (seção 25) — números do empreendimento próprio.
-- Fonte inicial: Gestor. Modelo preparado para futura integração sistêmica
-- sem alterar o modelo analítico.
-- UNIQUE(id_empreendimento, mes_ano).
-- ---------------------------------------------------------------------
create table if not exists dados_proprios_mensais (
  id_registro       uuid primary key default gen_random_uuid(),
  id_empreendimento integer not null references empreendimentos (id_empreendimento),
  mes_ano           date not null,
  estoque           integer not null check (estoque >= 0),
  vendas            integer not null check (vendas  >= 0),
  atualizado_por    uuid references gestores (id_gestor),
  atualizado_em     timestamptz not null default now(),
  constraint chk_dp_mes_ano_dia1 check (date_trunc('month', mes_ano) = mes_ano),
  constraint uq_dados_proprios_emp_mes unique (id_empreendimento, mes_ano)
);
create index if not exists idx_dados_proprios_id_emp  on dados_proprios_mensais (id_empreendimento);
create index if not exists idx_dados_proprios_mes_ano on dados_proprios_mensais (mes_ano);

-- ---------------------------------------------------------------------
-- Triggers de auditoria: manter updated_at / atualizado_em
-- ---------------------------------------------------------------------
create or replace function set_updated_at() returns trigger as $$
begin
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

create or replace function set_atualizado_em() returns trigger as $$
begin
  new.atualizado_em := now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_concorrentes_updated on concorrentes;
create trigger trg_concorrentes_updated before update on concorrentes
  for each row execute function set_updated_at();

drop trigger if exists trg_agentes_updated on agentes_campo;
create trigger trg_agentes_updated before update on agentes_campo
  for each row execute function set_updated_at();

drop trigger if exists trg_gestores_updated on gestores;
create trigger trg_gestores_updated before update on gestores
  for each row execute function set_updated_at();

drop trigger if exists trg_coletas_updated on coletas_mensais;
create trigger trg_coletas_updated before update on coletas_mensais
  for each row execute function set_atualizado_em();

drop trigger if exists trg_dados_proprios_updated on dados_proprios_mensais;
create trigger trg_dados_proprios_updated before update on dados_proprios_mensais
  for each row execute function set_atualizado_em();
